
<?php if($this->showReferralUrl() ||  $this->showReferralCode() ||  $this->showReferralEmail()): ?>
<!-- @nelkaake Added on Saturday June 26, 2010: BEGIN referral code/url/email fieldset -->
<fieldset class="group-select my_referrals-urlcode_group">
    <h4 class="legend"><?php echo $this->__('Referral Codes and URL'); ?></h4>
    <p><?php echo $this->__("You can use this information to refer other users to this site.  If you've already filled out the form to send a referral you dont have to give them this URL."); ?>
    <?php echo $this->__("You can choose use either the code or the referral URL, or a combination of both.  It's your choice."); ?></p>
    <ul>
        <?php if($this->showReferralUrl()): ?>
        <li>
            <div class="urlcode-input-box">
                <label for="referral_url"><?php echo $this->__('Your Referral URL') ?></label><br />
                <input type="text" readonly name="referral_url" value="<?php echo $this->getReferralUrl(); ?>" 
                    title="<?php echo $this->__('Your Referral URL') ?>" class="input-text" id="referral_url" />
            </div>
        </li>
        <?php endif; ?>
        <?php if($this->showReferralCode()): ?>
        <li>
            <div class="urlcode-input-box">
                <label for="referral_url"><?php echo $this->__('Your Referral Code') ?></label><br />
                <input type="text" readonly name="referral_code" value="<?php echo $this->getReferralCode(); ?>" 
                    title="<?php echo $this->__('Your Referral Code') ?>" class="input-text" id="referral_code" /> <BR />
            </div> <BR />
            <div class="urlcode_comment"><?php echo $this->__("If you're referral is using your code, they should enter the code at checkout or signup."); ?></div>
        </li>
        <?php endif; ?>
        <?php if($this->showReferralEmail()): ?>
        <li>
            <div class="urlcode-input-box">
                <label for="referral_url"><?php echo $this->__('Your Referral Email') ?></label><br />
                <input type="text" readonly name="referral_email" value="<?php echo $this->getReferralEmail(); ?>" 
                    title="<?php echo $this->__('Your Referral Email') ?>" class="input-text" id="referral_email" /> <BR />
            </div> <BR />
            <div class="urlcode_comment"><?php echo $this->__("If you're referral is using your e-mail, they should enter your e-mail address at checkout or signup."); ?></div>
        </li>
        <?php endif; ?>
    </ul>
</fieldset>
<?php endif; ?>
<!-- @nelkaake Added on Saturday June 26, 2010: END referral code/url/email fieldset -->
