
    
<?php echo $this->getChildHtml('refer_form_multi'); ?>
<?php if($this->showSendReferralForm()): ?>

    <div class="box-info">
        <div class="box-head">
            <h2><?php echo $this->__('Invite One Person') ?></h2>
        </div>
<form action="<?php echo $this->getUrl('rewardsref/customer/invite/') ?>" method="post" id="form-validate">
    <?php if($this->hasPredictedSignupPoints()): ?>
    <!-- div>
        <?php echo $this->__("You could up to %s for when your referral signs up.", $this->getPredictedSignupPoints()); ?>
    </div -->
    <?php endif; ?>
    <?php if($this->hasPredictedFirstOrderPoints()): ?>
    <!-- div>
        <?php echo $this->__("You could up to %s for when your referral makes their first order.", $this->getPredictedFirstOrderPoints()); ?>
    </div -->
    <?php endif; ?>
    
    <fieldset class="group-select" style="margin-bottom: 0px;">
        <ul>
            <li>
                <div class="input-box">
                    <label for="telephone"><?php echo $this->__('Friend\'s name') ?> <span class="required">*</span></label><br />
                    <input type="text" name="name" value="" title="<?php echo $this->__('Friend\' name') ?>" class="required-entry input-text" id="name" />
                </div>
                <div class="input-box">
                    <label for="fax"><?php echo $this->__('Friend\'s email address') ?> <span class="required">*</span></label><br />
                    <input type="text" name="email" id="email" title="<?php echo $this->__('Friend\'s email address') ?>" value="" class="required-entry input-text" />
                </div>
            </li>
            <li>
                <div>
                    <label for="msg"><?php echo $this->__('Short Message') ?> </label><br />
                    <textarea type="text" name="msg" value="" title="<?php echo $this->__('Short Message') ?>" 
                            class="input-text" id="msg" ></textarea>
                </div>
            </li>
        </ul>
    <div class="button-set" style="margin-top:0px">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <!--<a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>-->
        <button class="form-button" type="submit"><span><?php echo $this->__('Send') ?></span></button>
    </div>
    </fieldset>
</form>

<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>

</div>
<?php endif; ?>
